version: '3.1'

services:

  ps-db:
    container_name: pdb
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5455:5432"
  redis:
    container_name: cache
    image: redis:latest
    ports:
      - "6379:6379"
